export const REQUEST_PLAYING = 'REQUEST_PLAYING';
export const START_PLAYING = 'START_PLAYING';

export const REQUEST_BLEND_WITH_SELF = 'REQUEST_BLEND_WITH_SELF';
export const REQUEST_BLEND_WITH_OTHER = 'REQUEST_BLEND_WITH_OTHER';

export const FETCH_USER = 'FETCH_USER';
export const SET_USER = 'SET_USER';
export const UPDATE_USER_RGB = 'UPDATE_USER_RGB';
export const START_LOADING_USER = 'START_LOADING_USER';
export const END_LOADING_USER = 'END_LOADING_USER';


export const FETCH_PLAYERS = 'FETCH_PLAYER';
export const SET_PLAYERS = 'SET_PLAYERS';
export const UPDATE_PLAYER = 'UPDATE_PLAYER';
export const REQUEST_NEW_PLAYER = 'REQUEST_NEW_PLAYER';
export const ADD_NEW_PLAYER = 'ADD_NEW_PLAYER';
export const START_LOADING_PLAYERS = 'START_LOADING_PLAYERS';
export const END_LOADING_PLAYERS = 'END_LOADING_PLAYERS';

export const START_TRANSACTION = 'START_TRANSACTION';
export const END_TRANSACTION = 'END_TRANSACTION';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
