version: '3'

services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    command: --gasLimit 0xfffffffffff ${ACCOUNTS} -i 90451 -b 3
    ports:
      - 7545:8545

  # Some bug when using testrpc-sc in docker (jsonRPC does not seem accessible)
  # testrpc-sc:
  #  build:
  #     dockerfile: ./ganache/Dockerfile
  #     context: ..
  #   command: --gasLimit 0xfffffffffff ${ACCOUNTS}
  #   ports:
  #     - 8555:8555
  #   volumes:
  #     - ..:/usr/src/app
