export const START_PLAYING = 'START_PLAYING';

export const REQUEST_AUTO_BLEND = 'REQUEST_AUTO_BLEND';
export const REQUEST_BLEND = 'REQUEST_BLEND';
export const SET_BLENDING_PRICE = 'SET_BLENDING_PRICE';

export const GET_USER = 'GET_USER';
export const SET_USER = 'SET_USER';
export const UPDATE_USER_COLOR = 'UPDATE_USER_COLOR';
export const START_LOADING_USER = 'START_LOADING_USER';
export const END_LOADING_USER = 'END_LOADING_USER';

export const GET_PLAYERS = 'GET_PLAYERS';
export const SET_PLAYERS = 'SET_PLAYERS';
export const UPDATE_PLAYER_TOKEN = 'UPDATE_PLAYER_TOKEN';
export const NEW_PLAYER = 'NEW_PLAYER';
export const ADD_PLAYER = 'ADD_PLAYER';
export const START_LOADING_PLAYERS = 'START_LOADING_PLAYERS';
export const END_LOADING_PLAYERS = 'END_LOADING_PLAYERS';

export const START_TRANSACTION = 'START_TRANSACTION';
export const END_TRANSACTION = 'END_TRANSACTION';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';


export const START_LOADING_WEB3 = 'START_LOADING_WEB3';
export const END_LOADING_WEB3 = 'END_LOADING_WEB3';
export const SET_UP_WEB3 = 'SET_UP_WEB3';
export const SET_WEB3 = 'SET_WEB3';
